### ISSUE TITLE
Improve Styles 

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#13]
- [x] Make grey text more readable (darker or larger or lighten background) 
- [x] Fix header fonts 
- [x] Tighten spacing on navigation so accordion ideally fits on the screen 
- [x] Remove underscores from navigation 
- [x] Random stuff: under 2_Design "existing" is misaligned not sure why

**Comment by johnvf** [comment]
Resolved "Tighten spacing on navigation so accordion ideally fits on the screen" by allowing a scrollbar if accordion section exceeds allowable height
