### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#14]
Clarify map vs. text nav: 
- [ ] tooltip for "chapter" and "map layer" and for "toolbox" "map" 
- [x] make radio button stand out more? different color outline? 
  Text View 
- [x] make text box wider (does map view even make sense? really hard to read text) 
- [x] add button to next section at end of each chapter

**Comment by johnvf** [comment]
Some map layers do not correlate to text sections. Is the goal to eventually have a 1:1 correspondence between these two? 

If not, text sections in the map nav that do not navigate you to text sections would have to be grayed out (and this might feel a bit hacky/bad from a UX perspective)

**Comment by johnvf** [comment]
tooltip for "chapter" and "map layer" and for "toolbox" "map" - not sure what is meant by this

add button to next section at end of each chapter - can this be added to the text as a hyperlink?

**Comment by marishaf** [comment]
Tooltip is probably not the right way to say this. People were asking for a tutorial on the first page with pop ups and arrows and stuff so people know how to use the website.
