### ISSUE TITLE
map not going full screen inside the box 

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#20]
Sometimes when I resize or reload the map view, there is a blank space on the right of the map box

**Comment by marishaf** [comment]
Also, there is a bigger issue when expanding and minimizing the map box and or re-loading the page after the map has been expanded. Check this screen shot: 
![screen shot 2016-02-04 at 11 51 13 am](https://cloud.githubusercontent.com/assets/6758850/12827711/cd83d30c-cb35-11e5-89dc-9e7a1f83b9d3.png)

**Comment by marishaf** [comment]
This might be part of another problem. The entire screen creeps up when I open any menu item aside from "1_analyze" it does not go back down unless I refresh at the landing page.

**Comment by johnvf** [comment]
The map redraw thing has now been fixed.

The second issue was a consequence of changes I made to the menu to support responsive (other devices) styling. This has also now been fixed.
