### ISSUE TITLE
bug: text disappears after modal accessed through text 

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#21]
when clicking on a modal link in the text and then closing it through the close button or the x, the main text field has disappeared in the text box.

**Comment by johnvf** [comment]
This is a symptom of incorrect link URLs. The modal may still load, but many of the links have the old /analyze or /design (vs 1_analyze or 2_design). These links break the application. See "Direct removal of air pollution by trees in wind tunnel study" in 1_analyze for an example of a correctly formatted link.
