### ISSUE TITLE
Links in the toolbox take you to to the map 

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#35]
If you click a link in the toolbox that should go to another toolbox heading it instead opens that heading in the map 
![screen shot 2016-02-29 at 11 15 33 am](https://cloud.githubusercontent.com/assets/6758850/13406397/24a8e61c-ded8-11e5-9f79-ba2a352ba14c.png)

**Comment by johnvf** [comment]
Which link is causing this behavior?

**Comment by johnvf** [comment]
If I remember correctly, these links were not pointing to the correct URL. I'm closing this unless there is a specific example to of this behavior still happening.
