### ISSUE TITLE
weird notes at the end of toolbox 

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#37]
I can't see where these notes are coming from either in the google doc or the word doc. 
![screen shot 2016-02-29 at 12 47 03 pm](https://cloud.githubusercontent.com/assets/6758850/13408446/c5ddd632-dee2-11e5-8431-d89ff79d68d4.png)

**Comment by johnvf** [comment]
This is a footnote on page 27 of the .docx.

It must be the only footnote in the document. I would recommend removing it or changing it from a Word footnote to something embedded in the body of the document itself.
