### ISSUE TITLE
Map Zoom level and resolution different on certain computers  

### ISSUE THREAD

**Issue by marishaf** [johnvf/adapt-web-ui#39]
The map looks really bad on certain computers. On my 17" mac book pro it looks great on load. On Avi's 13" Mac Book Pro it looks really bad. It zooms to one small corner of the map area and all the styling looks really large. The points and lines are way too big and you can't see whats what. <Screen Shot 2016-03-19 at 10.13.17 AM.png>

**Comment by marishaf** [comment]
<img width="1163" alt="screen shot 2016-03-19 at 10 13 17 am" src="https://cloud.githubusercontent.com/assets/6758850/13900098/90a8b22e-edbb-11e5-8bf2-23aab2c2d3fd.png">

**Comment by johnvf** [comment]
It looks like others have had issues with lineweights/managing pixel resolution in MapboxGL - https://www.bountysource.com/issues/30042024-android-devices-performance-and-ppi

For now, setting a consistent pixel ratio should hopefully solve this:

**Comment by johnvf** [comment]
It looks like this issue is fixed - the scaling appears uniform on my phone/laptop. Closing this issue unless somebody else can verify this issue exists for them,
