### ISSUE TITLE
Glitch when scaling text

### ISSUE THREAD

**Issue by BioBricoleur** [johnvf/adapt-web-ui#40]
After you have selected an image form the resource section, whenever you try to scale the text box up or down, an image randomly pops up. It only seems to happen after  you've selected something already from the resource area.

**Comment by johnvf** [comment]
I'm having trouble reproducing this - can you send a gif or screenshots, or possibly screenshare at some point?

**Comment by johnvf** [comment]
Edit - I was able to reproduce this. Looking into a fix now

**Comment by BioBricoleur** [comment]
You rock!
