### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by BioBricoleur** [johnvf/adapt-web-ui#48]
Ideas?
Is this do to the massive amounts of demand streaming to the site? :)

<img width="1125" alt="screen shot 2016-04-26 at 2 28 28 pm" src="https://cloud.githubusercontent.com/assets/17955206/14834834/5f5f7c8e-0bbb-11e6-94a5-8baa81aa94d5.png">

**Comment by johnvf** [comment]
Hah, I think you caught a new build being deployed (I pushed a tweak at this time). Will reopen and investigate if this happens again.

**Comment by BioBricoleur** [comment]
Ha. No problem.
